# Generated by Django 6.0.7 on 2026-08-18 06:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_author_course_pdf_file'),
        ('institutions', '0003_institution_allowed_categories_and_more'),
        ('leads', '0001_initial'),
        ('partners', '0001_initial'),
        ('payments', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('note', 'Note')], default='note', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Scheduled follow-up time. Leave blank for a logged/completed activity.', null=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Projected deal value (INR).', max_digits=12)),
                ('probability_pct', models.PositiveIntegerField(default=20, help_text='0-100. Used for weighted forecasting.')),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='prospecting', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('website', 'Website Enquiry'), ('referral', 'Partner Referral'), ('cold_call', 'Cold Call'), ('walk_in', 'Walk-in'), ('social_media', 'Social Media'), ('event', 'Event / Exhibition'), ('other', 'Other')], default='website', max_length=20)),
                ('student_name', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('class_grade_interested', models.CharField(blank=True, max_length=20)),
                ('interested_in_olympiad', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial', 'Trial / Demo Class'), ('admission_offered', 'Admission Offered'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Inquiry',
                'verbose_name_plural': 'Student Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated no. of students, for revenue projection.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('coaching', 'Coaching Institute'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='In-house sales rep responsible for working this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Enquiry'), ('referral', 'Partner Referral'), ('cold_call', 'Cold Call'), ('walk_in', 'Walk-in'), ('social_media', 'Social Media'), ('event', 'Event / Exhibition'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Set if this lead was referred in by a franchise Partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo', 'Demo Scheduled'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='leads_lead_stage_4b0a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner'], name='leads_lead_owner_i_66e55a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up_date'], name='leads_lead_next_fo_917086_idx'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, help_text='Set once payment is actually collected for a Won deal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.opportunity'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='converted_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiry', to='institutions.student'),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='interested_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_inquiries', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_student_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='student_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='leads.studentinquiry'),
        ),
        migrations.AddField(
            model_name='activity',
            name='student_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.studentinquiry'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.CheckConstraint(condition=models.Q(('owner__isnull', False), ('partner__isnull', False), _connector='OR'), name='sales_target_needs_owner_or_partner'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['stage'], name='leads_stude_stage_51f8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['owner'], name='leads_stude_owner_i_38b0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['next_follow_up_date'], name='leads_stude_next_fo_93f9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage'], name='leads_oppor_stage_d5f0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner'], name='leads_oppor_owner_i_fcfc95_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='leads_oppor_expecte_8f5180_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('probability_pct__gte', 0), ('probability_pct__lte', 100)), name='opportunity_probability_0_100'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['due_date'], name='leads_activ_due_dat_1cc3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_completed'], name='leads_activ_is_comp_eb6890_idx'),
        ),
    ]
