# Generated by Django 6.0.7 on 2026-08-19 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_activity_opportunity_salestarget_studentinquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('coaching', 'Coaching Institute'), ('franchise', 'Franchise Partner'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Enquiry'), ('contact_page', 'Contact Page'), ('franchise_application', 'Franchise Application'), ('referral', 'Partner Referral'), ('cold_call', 'Cold Call'), ('walk_in', 'Walk-in'), ('social_media', 'Social Media'), ('event', 'Event / Exhibition'), ('other', 'Other')], default='website', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentinquiry',
            name='source',
            field=models.CharField(choices=[('website', 'Website Enquiry'), ('contact_page', 'Contact Page'), ('franchise_application', 'Franchise Application'), ('referral', 'Partner Referral'), ('cold_call', 'Cold Call'), ('walk_in', 'Walk-in'), ('social_media', 'Social Media'), ('event', 'Event / Exhibition'), ('other', 'Other')], default='website', max_length=30),
        ),
    ]
