# Generated by Django 6.0.7 on 2026-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_institution_type_alter_lead_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinquiry',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial', 'Trial / Demo Class'), ('talent_hunt_exam', 'Talent Hunt Exam'), ('ai_quotient', 'AI Quotient'), ('entrance_exam_ug_pg', 'Entrance Exam for UG/PG Admission'), ('admission_offered', 'Admission Offered'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
