# Generated by Django 6.0.7 on 2026-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_add_talent_hunt_assessment_guidance_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinquiry',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('trial', 'Trial / Demo Class'), ('talent_hunt_exam', 'Talent Hunt Exam'), ('talent_hunt', 'Talent Hunt'), ('assessment', 'Assessment'), ('guidance_counselling', 'Guidance & Counselling'), ('ai_quotient', 'AI Quotient'), ('entrance_exam_ug_pg', 'Entrance Exam for UG/PG Admission'), ('admission_offered', 'Admission Offered'), ('enrolled', 'Enrolled'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
