# Generated by Django 6.0.7 on 2026-07-21 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('investment_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_product_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_olympiad_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_services_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('joining_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('kyc_document', models.FileField(blank=True, null=True, upload_to='partner_kyc/')),
                ('bank_account_no', models.CharField(blank=True, max_length=30)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15)),
                ('territory', models.CharField(blank=True, max_length=100)),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partners', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partnercategory')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_file', models.FileField(upload_to='agreements/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='partners.partner')),
            ],
        ),
    ]
