# Generated by Django 6.0.7 on 2026-08-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Expense Head Name')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Expense Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Head',
                'verbose_name_plural': 'Expense Heads',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Expense Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₹)')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('paid_to', models.CharField(help_text='Vendor, Employee or Company Name', max_length=200, verbose_name='Paid To / Payee')),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer / NEFT / RTGS'), ('upi', 'UPI / PhonePe / GooglePay'), ('card', 'Corporate / Credit Card'), ('cheque', 'Cheque')], default='cash', max_length=30, verbose_name='Payment Mode')),
                ('reference_no', models.CharField(blank=True, max_length=100, verbose_name='Reference / Invoice / Txn No.')),
                ('receipt_attachment', models.FileField(blank=True, null=True, upload_to='expense_receipts/%Y/%m/', verbose_name='Receipt / Invoice File')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL)),
                ('expense_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensehead')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
