# Generated by Django 6.0.7 on 2026-08-18 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Designation Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True, verbose_name='Employee ID')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='Probation End Date')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number')),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, verbose_name='Bank IFSC Code')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('onboarding_status', models.CharField(choices=[('docs_pending', 'Documents Pending'), ('under_review', 'Under Review'), ('active', 'Active / Completed'), ('rejected', 'Rejected')], default='docs_pending', max_length=20, verbose_name='Onboarding Status')),
                ('notes', models.TextField(blank=True, verbose_name='HR Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_proof', 'ID Proof (Aadhaar/Passport/Govt ID)'), ('pan_card', 'PAN Card'), ('degree', 'Educational Certificate / Degree'), ('experience', 'Relieving / Experience Letter'), ('bank_proof', 'Bank Proof / Cancelled Cheque'), ('other', 'Other Document')], max_length=30, verbose_name='Document Type')),
                ('document_name', models.CharField(max_length=255, verbose_name='Document Name/Title')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/', verbose_name='Document File')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.employeeprofile')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, verbose_name='Task Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='accounts.employeeprofile')),
            ],
            options={
                'verbose_name': 'Onboarding Task',
                'verbose_name_plural': 'Onboarding Tasks',
            },
        ),
    ]
