# Generated by Django 6.0.7 on 2026-08-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_designation_employeeprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Holiday'), ('F', 'Half Day'), ('L', 'Late')], default='P', max_length=5, verbose_name='Status')),
                ('academic_year', models.CharField(default='2025/2026', max_length=20, verbose_name='Academic Year')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check In Time')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check Out Time')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='accounts_at_user_id_4cfdb0_idx'), models.Index(fields=['date'], name='accounts_at_date_20648b_idx'), models.Index(fields=['status'], name='accounts_at_status_2da0a5_idx'), models.Index(fields=['academic_year'], name='accounts_at_academi_124cef_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
