# Generated by Django 6.0.7 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_attendance_status_wfhrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfhrequest',
            name='leave_type',
            field=models.CharField(default='Work From Home (WFH)', max_length=100, verbose_name='Leave Type'),
        ),
    ]
