# Generated by Django 6.0.7 on 2026-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wfhrequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wfhrequest',
            name='target_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Email'),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='target_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Name'),
        ),
    ]
