# Generated by Django 6.0.7 on 2026-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employeeprofile_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Check In IP'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Check In Latitude'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Check In Location'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Check In Longitude'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Check Out IP'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Check Out Latitude'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Check Out Location'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Check Out Longitude'),
        ),
    ]
