# Generated by Django 6.0.7 on 2026-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_attendance_check_in_ip_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_check_in_time', models.TimeField(default='09:30:00', verbose_name='Office Check-In Time')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, verbose_name='Grace Period (Minutes)')),
                ('office_check_out_time', models.TimeField(default='18:30:00', verbose_name='Office Check-Out Time')),
                ('office_location_name', models.CharField(default='Main Head Office', max_length=255, verbose_name='Office Location Name')),
                ('office_latitude', models.FloatField(blank=True, null=True, verbose_name='Office Latitude')),
                ('office_longitude', models.FloatField(blank=True, null=True, verbose_name='Office Longitude')),
                ('geofence_radius_meters', models.PositiveIntegerField(default=500, verbose_name='Geofence Radius (Meters)')),
                ('enforce_geofence', models.BooleanField(default=False, verbose_name='Enforce Geofence Validation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Setting',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
    ]
