# Generated by Django 6.0.7 on 2026-09-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_suspended_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, help_text='ID of the customer created in Razorpay for tokenization.', max_length=50, null=True, verbose_name='Razorpay Customer ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
