# Generated by Django 6.0.7 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_classes',
            field=models.CharField(blank=True, help_text='Comma separated classes this teacher is assigned to (e.g. Class 10 (A), Class 9)', max_length=255, verbose_name='Assigned Classes'),
        ),
    ]
