# Generated by Django 6.0.7 on 2026-09-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_assigned_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_classes',
        ),
    ]
