# Generated by Django 6.0.7 on 2026-07-25 07:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
        ('partners', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('color_code', models.CharField(default='#0066cc', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuizAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accessed', 'Quiz Accessed'), ('started', 'Quiz Started'), ('submitted', 'Quiz Submitted'), ('viewed', 'Quiz Viewed in Admin'), ('modified', 'Quiz Modified'), ('published', 'Quiz Published')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz Access Log',
                'verbose_name_plural': 'Quiz Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['course', 'order']},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Quiz Attempt', 'verbose_name_plural': 'Quiz Attempts'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['quiz', 'order'], 'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='attempted_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='question_text',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_files/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_anti_cheating',
            field=models.BooleanField(default=True, help_text='Enable anti-cheating measures'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_key',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique encrypted key for quiz', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='randomize_options',
            field=models.BooleanField(default=True, help_text='Randomize answer options'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='requires_authentication',
            field=models.BooleanField(default=True, help_text='Require user authentication'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers',
            field=models.BooleanField(default=True, help_text='Show after completion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_per_student',
            field=models.BooleanField(default=True, help_text='Different randomization per student'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=True, help_text='Randomize question order'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='_student_responses_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted student responses (JSON)'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='cheating_details',
            field=models.TextField(blank=True, help_text='Details of cheating detection'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='cheating_detected',
            field=models.BooleanField(default=False, help_text='Potential cheating detected'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='score_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='session_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address during attempt', null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='session_token',
            field=models.CharField(default=django.utils.timezone.now, help_text='Unique session identifier (encrypted)', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('flagged', 'Flagged for Review')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_correct_option_encrypted',
            field=models.CharField(default='', help_text='Encrypted correct answer', max_length=100),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_explanation_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted explanation'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_option_a_encrypted',
            field=models.CharField(default='', help_text='Encrypted option A', max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_option_b_encrypted',
            field=models.CharField(default='', help_text='Encrypted option B', max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_option_c_encrypted',
            field=models.CharField(default='', help_text='Encrypted option C', max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_option_d_encrypted',
            field=models.CharField(default='', help_text='Encrypted option D', max_length=500),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='_question_text_encrypted',
            field=models.TextField(default='', help_text='Encrypted question'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text/Article'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('live', 'Live Class'), ('assignment', 'Assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.OneToOneField(limit_choices_to={'content_type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score_pct',
            field=models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='marks',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'student', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'is_published'], name='courses_cou_course__bb8a81_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_completed'], name='courses_enr_student_e7d582_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'enrolled_at'], name='courses_enr_course__e014c4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['institution'], name='courses_enr_institu_c7de96_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'is_published'], name='courses_les_module__ba1aef_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='courses_les_content_d3cec9_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_key'], name='courses_qui_quiz_ke_a5f709_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='courses_qui_is_acti_3bda0c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'started_at'], name='courses_qui_student_3225df_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'passed'], name='courses_qui_quiz_id_eefb36_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz'], name='courses_qui_quiz_id_a9f614_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['is_active', 'order'], name='courses_cou_is_acti_1dc218_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecategory',
            index=models.Index(fields=['slug'], name='courses_cou_slug_6be797_idx'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_cou_slug_2e551f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='courses_cou_status_96f2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='courses_cou_categor_c23a2b_idx'),
        ),
        migrations.AddField(
            model_name='quizaccesslog',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='quizaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quizaccesslog',
            index=models.Index(fields=['quiz', 'timestamp'], name='courses_qui_quiz_id_e019b2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='courses_qui_user_id_71075f_idx'),
        ),
    ]
