# Generated by Django 6.0.7 on 2026-07-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursecategory_quizaccesslog_alter_course_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='courses_enr_student_e7d582_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='courses_enr_course__e014c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='courses_enr_institu_c7de96_idx',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='completed_at',
            new_name='completion_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_accessed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='referred_by_partner',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_at',
        ),
    ]
