# Generated by Django 6.0.7 on 2026-08-07 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
