# Generated by Django 6.0.7 on 2026-08-18 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_author_course_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, default='', help_text="Student's typed response or notes")),
                ('submission_file', models.FileField(blank=True, help_text='Uploaded submission file', null=True, upload_to='assignment_submissions/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('skipped', 'Skipped for now')], default='submitted', max_length=20)),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(limit_choices_to={'content_type': 'assignment'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-updated_at'],
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
