# Generated by Django 6.0.7 on 2026-09-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
    ]
