# Generated by Django 6.0.7 on 2026-07-21 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('partners', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=9)),
                ('level', models.CharField(choices=[('school', 'School Level'), ('zonal', 'Zonal'), ('national', 'National')], default='school', max_length=10)),
                ('class_group', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('syllabus_pdf', models.FileField(blank=True, null=True, upload_to='olympiad_syllabus/')),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('exam_date', models.DateTimeField()),
                ('exam_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olympiad.olympiadcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='olympiad.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_plan_credit', models.BooleanField(default=False)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('admit_card_issued', 'Admit Card Issued'), ('appeared', 'Appeared'), ('absent', 'Absent')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='olympiad.olympiad')),
                ('referred_by_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
            options={
                'unique_together': {('olympiad', 'student')},
            },
        ),
        migrations.CreateModel(
            name='OlympiadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='olympiad.olympiadregistration')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank_school', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_zonal', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_national', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('participation', 'Participation')], max_length=15)),
                ('certificate_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='olympiad.olympiadregistration')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('scholarship_type', models.CharField(choices=[('fee_waiver', 'Fee Waiver on Next Registration'), ('cash_award', 'Cash Award'), ('course_credit', 'Free Course Credit')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_bands', to='olympiad.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('gold_medal', 'Gold Medal'), ('silver_medal', 'Silver Medal'), ('bronze_medal', 'Bronze Medal'), ('certificate', 'Certificate of Excellence'), ('scholarship', 'Scholarship')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('certificate_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='olympiad.olympiadresult')),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.olympiadscholarship')),
            ],
        ),
    ]
