# Generated by Django 6.0.7 on 2026-08-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_olympiad_result_declaration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='next_day_release_time',
            field=models.TimeField(default='09:00:00', help_text="Release time for 'Next Day' result mode"),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='result_display_mode',
            field=models.CharField(choices=[('immediate', 'Instant Result'), ('after_2_hours', 'After 2 Hours of Submission'), ('next_day', 'Next Day (Following Day)'), ('scheduled', 'Scheduled Specific Date/Time'), ('manual', 'Manual Release')], default='immediate', max_length=20),
        ),
    ]
