# Generated by Django 6.0.7 on 2026-08-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_olympiad_next_day_release_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='is_entrance_exam',
            field=models.BooleanField(default=True, help_text='Designates if this exam is an Olympiad Entrance Exam'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_result_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='result_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='result_timing_mode',
            field=models.CharField(choices=[('immediate', 'Instant Result'), ('after_2_hours', 'After 2 Hours of Submission'), ('next_day', 'Next Day (Following Day)'), ('scheduled', 'Scheduled Specific Date/Time'), ('manual', 'Manual Release')], default='immediate', max_length=20),
        ),
    ]
