# Generated by Django 6.0.7 on 2026-08-20 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the team member', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL slug (auto-generated if empty)', max_length=220, unique=True)),
                ('designation', models.CharField(help_text='e.g. AI Lab Mentor, Olympiad Lead, CEO', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='team/')),
                ('quote', models.TextField(blank=True, default='', help_text='Inspirational quote or motto')),
                ('bio', models.TextField(blank=True, default='', help_text='Detailed biography or introduction')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('whatsapp_url', models.CharField(blank=True, default='', max_length=150)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, default='', help_text='Education & Qualifications history (e.g. year / degree / institute)')),
                ('experiences', models.TextField(blank=True, default='', help_text='Detailed experience summary and career achievements')),
                ('skills_overview', models.TextField(blank=True, default='', help_text='Key skills and proficiency levels (e.g. Completed Projects: 80, Financial Skills: 95)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility across the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author_name', models.CharField(blank=True, default='EduAiQ Team', max_length=150)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('summary', models.TextField(blank=True, default='', help_text='Short excerpt for cards, social share, and search results')),
                ('content', models.TextField(help_text='Full blog post content (HTML supported)')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags e.g. AI Skills, Olympiads, Careers', max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured blog sections')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.blogcategory')),
                ('author_team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='content.teammember')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
