# Generated by Django 6.0.5 on 2026-08-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_enrollment_options_and_more'),
        ('institutions', '0002_student_delete_institutionstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='institution',
            name='allowed_courses',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='courses.course'),
        ),
    ]
