# Generated by Django 6.0.7 on 2026-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institution_assigned_employee_institution_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
