# Generated by Django 6.0.7 on 2026-09-14 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_student_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_user',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'parent'}, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
